# This is a basic workflow to help you get started with Actions
name: Archive firmware page

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 */7 * *" # Run every 7 days at midnight UTC
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  archive:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Archive the Kindle Fire firmware downloads page
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/gp/help/customer/display.html?nodeId=G2JXLC4L34GX73TE"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
          
  # This workflow contains a single job called "build"
  archive-11th-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Fire HD 10 (11th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HD10_11th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
      
      - name: Fire HD 10 Plus (11th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HD10_Pro_11th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          
  # This workflow contains a single job called "build"
  archive-10th-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Fire HD 8 (10th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HD8_10th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
          
      - name: Fire HD 8 Plus (10th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HD8_Plus_10th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
          
  # This workflow contains a single job called "build"
  archive-9th-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Fire HD 10 (9th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HD10_9th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
          
      - name: Fire 7 (9th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_7_9th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
      
  archive-8th-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Fire HD 8 (8th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HD8_8th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
  
  archive-7th-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Fire HD 10 (7th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HD10_7th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
  
      - name: Fire HD 8 (7th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HD8_7th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
          
      - name: Fire (7th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_7th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
          
  archive-6th-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Fire HD 8 (6th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HD8_6th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
          
  archive-5th-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Fire HD 10 (5th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HD10_5th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
          
      - name: Fire HD 8 (5th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HD8_5th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
          
      - name: Fire (5th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_5th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
      
  archive-4th-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Fire HDX 8.9 (4th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HDX8.9_4th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
          
      - name: Fire HD 7 (4th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_5th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
          
      - name: Fire HD 6 (4th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_5th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
      
  archive-3rd-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
  archive-2nd-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
  archive-1st-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
