# This is a basic workflow to help you get started with Actions
name: Archive firmware page

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 11,26 * *" # Run on 11th and 26th at midnight UTC
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  archive-9th-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Fire HD 10 (9th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_HD10_9th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
          
      - name: Fire 7 (9th Generation)
        uses: JamieMagee/wayback@v1.3.15
        with:
          url: "https://www.amazon.com/update_Fire_7_9th_Gen"
          saveErrors: true # optional, default is true
          saveOutlinks: true # optional, default is false
          saveScreenshot: false # optional, default is false
