# This is a basic workflow to help you get started with Actions
name: Archive 4th generation firmware files

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 1,16 * *" # Run on 1st and 16th at midnight UTC
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 
  archive-4th-gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Fire HDX 8.9 (4th Generation)
        uses: JamieMagee/wayback@v1.3.28
        with:
          url: "https://www.amazon.com/update_Fire_HDX89_4th_Gen"
          
      - name: Fire HD 7 (4th Generation)
        uses: JamieMagee/wayback@v1.3.28
        with:
          url: "https://www.amazon.com/update_FireHD7_4th_Gen"
      
      - name: Fire HD 6 (4th Generation)
        uses: JamieMagee/wayback@v1.3.28
        with:
          url: "https://www.amazon.com/update_FireHD6_4th_Gen"
